#!/bin/sh

# basic verbosity
alias \
	cp="cp -iv"\
	mv="mv -iv"\
	rm="rm -vI"\
	mkd="mkdir -pv"\
	ps="ps --forest"

# basic colors when possible
alias \
	ls="ls -hN --color=auto --group-directories-first"\
	grep="grep --color=auto"\
	diff="diff --color=auto"

# long commands -> shrt cmds
alias \
	g="git"\
	sdn="shutdown -h now"\
	e="$EDITOR"\
	v="$EDITOR"\
	a="sudo apt"\
	z="zathura"\
	cpl="make distclean && make all && make clean"

# change output if not possible by env
alias \
	wget="wget --hsts-file=$HOME/.cache/wget-hsts"\
	dosbox="dosbox -conf "$XDG_CONFIG_HOME"/dosbox/dosbox.conf"

# change to other commands
alias \
	lf="lfcd"
